### ISSUE TITLE
What's the algo of this coin ?

### ISSUE THREAD

**Issue by RobinHooD1024** [BancCoin/banccoin-core#1]
On some docs you mentioned Tribus algo, on sources you have Scrypt. So what's algo did you use ?

**Comment by BancCoinOriginal** [comment]
Initially we started as Tribus.  However, we were having some difficulties on some platforms, so we updated to Script algo. Now we are trading on https://p2pb2b.io and we are about to announce a second platform (as soon as listing is complete).  Thanks for asking.
